magnet_motion:
  motion:
    parent_frame: "world"
    child_frame: "magnet"
    mode: translate_and_rotate
    axis: z
    angular_velocity: 1.0
    initial_roll: 0.0
    initial_pitch: 0.0
    initial_yaw: 0.0
    static_position: [0.0, 0.0, 0.0]
    static_orientation: [0.0, 0.0, 0.0]
  path:
    width: 0.03
    height: 0.03
    z: 0.03
    center:
      x: 0.02
      y: 0.02
    update_rate: 100.0
    velocity: 0.01
