config:
  frame:
    parent: sensor_array/base
    child: magnet/base
  motion:
    update_rate_hz: 120.0
    magnetic_strength: 5.0
  tf:
    enable: true
    static: false
  topics:
    pose: /magnetic/pose_true
  trajectory:
    type: circular
    center: [0.0, 0.0, 0.045]
    radius: 0.045
    angular_speed: 0.8
    phase: 0.0
    orientation_rpy: [0.0, 0.0, 0.0]
  orientation:
    mode: spin
    initial_rpy: [0.0, 0.0, 0.0]
    angular_velocity: 0.6
    axis: z
