# 磁体设备配置
config:
  frames:
    parent: world
    child: magnet
  topics:
    pose: /magnetic/pose_true
  motion:
    update_rate_hz: 60.0  # 磁铁位姿更新频率 (Hz)，与传感器同步
    magnetic_strength: 10.0 
  tf:
    enable: true
    static: false
  trajectory:
    type: rectangular
    rectangular:
      width: 0.3                   # 宽度（米）
      height: 0.3                   # 高度（米）
      center_xyz: [0.5, 0, 1.2]  # 中心位置 [x, y, z]（米），z 为矩形轨迹的高度
      velocity: 0.02                 # 线速度（米/秒）
      orientation_rpy: [0.0, 0.0, 0.0]  # 姿态 [roll, pitch, yaw] (弧度)
    
  orientation:
    mode: spin
    spin:
      axis: xyz
      angular_velocity: 1.0
      initial_rpy: [0.0, 0.0, 0.0]

