pose_topic: ""
estimated_pose_topic: "/magnetic/pose_estimated"
enable_estimated_pose: true
enable_true_pose: false
frame_id: "sensor_array/base"
marker_ns: "magnet_hw"
estimated_marker_ns: "magnet_est"
trail_size: 400
trail_duration: 30.0
trail_min_distance: 0.002
trail_width: 0.0025
estimated_trail_width: 0.0025
magnet_length: 0.05
magnet_radius: 0.01
marker_lifetime: 0.0
show_strength_text: false
