config:
  frame:
    parent: world
    child: magnet
  motion:
    update_rate_hz: 60.0
    magnetic_strength: 5.0
  tf:
    enable: true
    static: true
  topics:
    pose: /magnetic/pose_true
  trajectory:
    type: static
    pose:
      xyz: [0.0, 0.0, 0.05]
      rpy: [0.0, 0.0, 0.0]
