config:
  arms:
    - name: magnet
      group_name: fr5v6_magnet_arm
      end_effector_link: magnet_arm_tool
      reference_frame: world
      default_velocity: 0.3
      default_acceleration: 0.3
      planning_time: 5.0
      allow_replanning: false
      goal_position_tolerance: 0.005
      goal_orientation_tolerance: 0.01
      default_named_target: home
      base_tf:
        parent: world
        child: magnet_arm_base
        pose:
          xyz: [0.0, 0.0, 0.0]
          rpy: [0.0, 0.0, 0.0]
      named_targets:
        - name: up
          target: up
        - name: ready
          target: ready

    - name: sensor
      group_name: fr5v6_sensor_arm
      end_effector_link: sensor_arm_tool
      reference_frame: world
      default_velocity: 0.3
      default_acceleration: 0.3
      planning_time: 5.0
      allow_replanning: false
      goal_position_tolerance: 0.005
      goal_orientation_tolerance: 0.01
      default_named_target: home
      base_tf:
        parent: world
        child: sensor_arm_base
        pose:
          xyz: [0.4, -0.2, 0.0]
          rpy: [0.0, 0.0, 0.0]
      named_targets:
        - name: home
          target: home
        - name: ready
          target: ready

