config:
  arms:
    - name: magnet
      group_name: fr5v6_arm
      end_effector_link: frrobot_tool_link
      reference_frame: world
      default_velocity: 0.1
      default_acceleration: 0.1
      planning_time: 5.0
      allow_replanning: false
      goal_position_tolerance: 0.005
      goal_orientation_tolerance: 0.01
      default_named_target: ready
      base_tf:
        parent: world
        child: magnet_arm_base
        pose:
          xyz: [0.0, 0.0, 0.0]
          rpy: [0.0, 0.0, 0.0]
      named_targets:
        - name: ready
          target: ready
        - name: up
          target: up
      tool_mount:
        selected: magnetic_sensor_bracket
        options:
          - name: magnetic_sensor_bracket
            frame: magnet_sensor_tool
            parent_frame: frrobot_tool_link
            mesh: package://mag_device_arm/meshes/magnetic_sensor_bracket.STL
            pose:
              xyz: [0.0, 0.0, 0.0]
              rpy: [1.5708, 0.0, -1.5708]
            scale: [0.001, 0.001, 0.001]
          - name: none
            frame: magnet_arm_tool_mount
            parent_frame: frrobot_tool_link
            pose:
              xyz: [0.0, 0.0, 0.0]
              rpy: [0.0, 0.0, 0.0]
