config:
  arms:
    - name: magnet
      group_name: fr5v6_arm
      end_effector_link: frrobot_tool_link
      reference_frame: world
      default_velocity: 0.1
      default_acceleration: 0.1
      planning_time: 5.0
      allow_replanning: false
      goal_position_tolerance: 0.005
      goal_orientation_tolerance: 0.01
      default_named_target: ready
      base_tf:
        parent: world
        child: magnet_arm_base
        pose:
          xyz: [0.0, 0.0, 0.0]
          rpy: [0.0, 0.0, 0.0]
      named_targets:
        - name: ready
          target: ready
        - name: up
          target: up

