config:
  frames:
    parent: world
    child: magnet
  topics:
    pose: /magnetic/pose_true
  motion:
    update_rate_hz: 60.0
    magnetic_strength: 900000.0
  tf:
    enable: true
    static: true
  trajectory:
    type: static
    static:
      pose:
        xyz: [0.6, 0.0, 1.1]
        rpy: [0.0, 0.0, 0.0]
  orientation:
    mode: trajectory

